"""empty message

Revision ID: 42cdce30ca32
Revises: 7ba9c547e144
Create Date: 2025-04-21 19:08:07.751989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cdce30ca32'
down_revision = '7ba9c547e144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isComplete', sa.String(length=225), nullable=True))
        batch_op.alter_column('receiver_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('receiver_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('isComplete')

    # ### end Alembic commands ###
